class Acrostic
  def initialize
    @poem = ""
  end
  def generate(word)
    stanza = {}
    warn TITLE[Random.rand(TITLE.length)]
    warn "------------------------------"
    word.upcase!
    word.each_char do |letter|
      if letter === " "
        warn " "
      elsif stanza[letter]
        warn stanza[letter]
      else
        idx = Random.rand(LYRICS[letter].count)
        stanza[letter] = LYRICS[letter][idx]
        warn stanza[letter]
      end
    end
    @poem
  end

  def warn s
    @poem = @poem + "\n#{s}"
    puts s
  end

  LYRICS =
  {9 => ["99 ways to die"],
  "A" => ["A cut-out cardboard condo maze",
  "A more efficient maniac",
  "A playground of illusion",
  "A blink of an eye between",
  "A book written by man",
  "A conspiracy of silence",
  "A country that's divided",
  "A credit to dementia",
  "A crosswalk hit and run",
  "A dark black past is mine",
  "A haven for those who walk this world",
  "A hole in my heart, a hole in my head?",
  "A killing machine",
  "A knife right through my heart, I am a victory",
  "A long shit list",
  "A must - have or you shall pay",
  "A peaceful man stands tall",
  "A plan of dignity and balance for all",
  "A playground for the demented",
  "A retreat for the damned",
  "A shorter fuse",
  "A snake you were when we met",
  "A soul mate to love",
  "A tiptoe through the darkness",
  "A toppled leader dies",
  "A worldwide suicide",
  "A'roll...",
  "A'warring for the heavens",
  "Ain't got no last words to say",
  "And a shot of thorazine",
  "And again and again, again",
  "And it's time to write my will",
  "And strung out just the same",
  "And the bars are gonna break",
  "And the taste blew my mind",
  "And when the story takes a twist",
  "Angry again, angry again, angry",
  "Angry again, angry again, angry again",
  "Angry again, angry again, angry ow",
  "As music rubber hosed the air",
  "Association that I choose",
  "Abandoned for wreckage nobody cares",
  "Acting like a robot",
  "Again we stalk the stage",
  "Ah yes you're all sitting ducks",
  "Ain't no pay back time",
  "All are gone, all but one",
  "All day long I think of things but nothing seems to satisfy",
  "All my plans denied",
  "All pay the price",
  "All rights will be denied",
  "All that I command",
  "All that I desire",
  "All these normal people, will I find another one?",
  "Am I a weak man, are you feeling strong?",
  "Am I dreaming? my heart pounds my chest",
  "An ego boost don't think twice",
  "An insane place, with insane moves",
  "And \"countdown to extinction\"",
  "And I can see there's something wrong with you",
  "And I play them to my chest",
  "And I will introduce you to",
  "And I'm feeling mean",
  "And I'm gettin' shot down",
  "And all the reasons I give you to bitch",
  "And as charon sails the sea",
  "And as my body decays mold begins to fill my grave",
  "And beg salvation from the empty skies",
  "And come to foreign lands",
  "And darkness fell upon our people",
  "And everybody rose, the reverend smith",
  "And feel your life is just a losing game",
  "And forever cunning",
  "And guarantees you'll lose",
  "And how I make you wanna scream in pain",
  "And how you cry for it all to stop",
  "And how you try to hold me down",
  "And make believe there's nobody else",
  "And much too late I realize",
  "And my air is getting thin",
  "And my memories left with you",
  "And my misfits way of life",
  "And my will to kill",
  "And now I fill your brain",
  "And now we are on a mission",
  "And now we're making up our minds",
  "And organic",
  "And put him in control",
  "And rides the seven-headed beast",
  "And should we really care",
  "And showing up on time is late",
  "And smile its blacktooth grin",
  "And so as you hear these words telling you now of my state",
  "And soon you'll meet your death",
  "And stay an inch or two outta kicking distance",
  "And taking down the names",
  "And that you say you will pray for me",
  "And the antichrist",
  "And the children, they were born faceless",
  "And the days where black as night",
  "And the flames rise to the sky",
  "And the lack of mercy killings.",
  "And the living are scarred",
  "And the sanity they lose",
  "And the soldiers liberate them, laying mines along their roads",
  "And their people, retrograde them",
  "And they'll set me free",
  "And when all is won and lost",
  "And when all is won and lost",
  "And when up he wakes ",
  "And when you kill a man, you're a murderer",
  "And you feel a sudden chill",
  "And you know I will",
  "And you will take my name",
  "And your face when I see you break",
  "Angel in our pocket, devil by our side",
  "Another long lost friend",
  "Another show's around the bend",
  "Another species of life form",
  "Anxiety's attacking me, and",
  "Are never satisfied",
  "Are worthless now, dead without a dead",
  "Are you lonely, all needs catered",
  "Are you lonely, you got no-one",
  "Arms in employ",
  "As I read our epitaph",
  "As I tuck you into bed",
  "As I'm taking all your money",
  "As for me I hocked my brains",
  "As humans' flesh leads the mind",
  "As pre-historic as it seems",
  "As the money that you bet",
  "As they bury me now six feet there my body lies",
  "Ask the sheep, for their beliefs",
  "Ask what your country can do for you",
  "Assailant from hell",
  "Assassin in stealth",
  "At least I gotta know what I wanna be",
  "At mach speed we engage",
  "At the start of time",
  "Awakened in the morning",
  "Aware of my immediate surrounding"],
  "B" => ["But when I seek out your voice",
  "Back in the bus again",
  "Back to the start, talk of the part",
  "Backed in a corner, caught up in the race",
  "Bad times are contagious",
  "Bang... it happened",
  "Barren land that once filled a need",
  "Battle plan running",
  "Battles without, for battles within",
  "Be as great as you want me to be",
  "Bearing down on me",
  "Beat out my brains",
  "Because I don't say it, don't mean I ain't thinking it",
  "Before he got there",
  "Before the head explodes",
  "Beginning of the end",
  "Behind the lines",
  "Believed foretold but who'd suspect",
  "Bereft of heart and soul",
  "Bestow upon me magic",
  "Bet you thought you had it all worked out",
  "Bet you thought you knew what I was about",
  "Bet you thought you'd solved all your problems",
  "Better left for dead",
  "Black curtains... never ending",
  "Black curtains... never ending, fall",
  "Black, blanket welcome",
  "Blah, blah, blah my soul to keep",
  "Blood of heroes",
  "Blood stains on my hands and",
  "Blood... is boiling",
  "Blue sky, black death",
  "Bomb shelters filled to the brim",
  "Born from the dark",
  "Born from the dark,",
  "Born unto themselves",
  "Boy! ... your soul better belong to jesus! ...",
  "Break new ground of a new frontier",
  "Break their pride, denigrate them",
  "Breaking them up, just breaking them in",
  "Brother will kill brother",
  "Burning inside",
  "But I don't even trust me",
  "But I know there's a reason,",
  "But dammit, this well's gone dry",
  "But don't try doing it to me",
  "But if you try to cut us out",
  "But keep it in the family tree",
  "But looking back it's still a bit fuzzy",
  "But now I'm safe in the eye of the tornado",
  "But some crazy shit has happened since \"the conjuring\"",
  "But we do it for the fame, yeah",
  "But won't take his hair",
  "But you are the problem",
  "But you end up driven to the ground",
  "By the skin o'my teeth",
  "By the skin of our teeth, now it's killing time",
  "By the way son here's",
  "By virtue of the jury's decision and the power"],
  "C" => ["Cause I've burned out my today",
  "Call him psychotron",
  "Came \"anarchy\" to \"set the world a fire\"",
  "Came the spawning of christ",
  "Can you help me occupy my brain?",
  "Can't do what I really feel",
  "Can't find no place to run",
  "Can't say what's on my mind",
  "Can't seem to smile 'till someone's sad",
  "Captive honour, ain't no honour",
  "Catatonic state",
  "Cause I could",
  "Cause a big nothing it'll be for me",
  "Cease to speak or cease to breathe",
  "Chalklines and red puddles of those who have been slain",
  "Chased up all the dead end streets",
  "Claiming validity",
  "Clinging on to life",
  "Cobwebs make me squint",
  "Cold as hell black as spades",
  "Come drink now of this curse",
  "Computer banks to rule the world",
  "Computer on-board",
  "Control's the illusion with all good intent",
  "Corruption of the world \"peace sells... but nobody's buying\"",
  "Country can spare",
  "Crash into the ground",
  "Criticist, the word that fits"],
  "D" => ["D-day, next stop normandie",
  "Demitasse of arsenic",
  "Down another glass of courage",
  "Damned if I'll be dead",
  "Dave your mental anyway hey!",
  "Deliver to the light",
  "Deliver to the light.",
  "Deluge from the wounds",
  "Destiny, that crooked schemer, says the dead shall rise again",
  "Dethrone the evil prince's iron fists",
  "Dirt grits beneath me feet",
  "Discharge my payload a mile high",
  "Do as you say",
  "Do it if you dare",
  "Do you kill on god's command?",
  "Dogs... are chasing",
  "Don't ask what you can do for you country",
  "Don't come to me if you need pity",
  "Don't let me down, don't give up, don't give in",
  "Don't look now to israel",
  "Don't push me, you piece of s**t!",
  "Don't remember where I was",
  "Don't wait to see what's next",
  "Don't want no revenge",
  "Don't you give me any orders",
  "Down in my pulpit as the holier",
  "Down in my seat of judgement",
  "Down... I'm drowning",
  "Dragons sleeping in my veins",
  "Dreams are told of dreams of old",
  "Drift into a deeper state",
  "Dropping all my weight"],
  "E" => ["Enforce a mental overload",
  "Engaged in crime I grasp my throat",
  "Enraged my mind starts to smoke",
  "Eat your heart out on a plastic tray",
  "Either way they die.",
  "Electricity, master all of these,",
  "Elysian fields...",
  "Empty jars of sleeping pills",
  "Endangered species, caged in fright",
  "Energy of the gods, adrenalin surge",
  "Engaged in a war",
  "Ensuing power vacuum",
  "Entering a near",
  "Entrails in the sky",
  "Epidemic, devastate them",
  "Eradication of earths",
  "Escape... you're joking",
  "Everything's helter-skelter",
  "Examining my head",
  "Exhilarating high"],
  "F" => ["Filled with an insubordinate race",
  "Fracture it's jaw to let me be",
  "Faceless as the snow",
  "Fasten up your head belts",
  "Faster as I go",
  "Fat lady dies",
  "Fate... is coming",
  "Feeding people's rage",
  "Feel the agony of defeat",
  "Feel velocity gain",
  "Feeling claustrophobic",
  "Feeling paranoid",
  "Fill the cracks in, with judicial granite",
  "Finished with my woman 'cause she couldn't help me with my mind",
  "Fire in my veins",
  "Fire... meltdown",
  "First mistake...last mistake!",
  "First time you touched me",
  "Flowing constantly",
  "Fools like me, who cross the sea",
  "For \"looking down the cross\" my \"skull beneath the skin\"",
  "For what they really are",
  "For you see the steel is much too strong",
  "For your stupidity",
  "Foreclosure of a dream",
  "Foreign life forms inventory",
  "Forever ... and the rate is accelerating",
  "Forever trusting",
  "Forgotten things remembered",
  "From a rock star to a desk fool",
  "From where she speaks",
  "Full assault fire threat",
  "Funny thing, he's like you & me"],
  "G" => ["Game I inevitably lose",
  "Gotta' short between the earphones",
  "Gotta' terminal future",
  "Governed by laws set up by me",
  "Gravity's got my bones",
  "Gavel's bang, uphold the law",
  "Get it right, terminate them",
  "Give me alchemy, give me sorcery",
  "Give me wizardy, thermatology",
  "Go to hell",
  "God have mercy!",
  "God something must've gone wrong",
  "Godspeed in glide",
  "Going down full throttle",
  "Going to war, give 'em hell",
  "Got on chance, infiltrate them",
  "Great nations built from the bones of the dead"],
  "H" => ["Had fingers in my eyes, had needles in my veins",
  "Hair... is burning",
  "Hangar 18 I know too much.",
  "Hanging up, I wanted to cry",
  "Happiness I cannot feel and love to me is so unreal",
  "Have you reached a verdict?",
  "He is untouchable",
  "He once had to be all he could be",
  "He recognized me",
  "He who lives by the swordhe who lives by the sword",
  "He who lives in sinhe who lives in sin",
  "Held for ransom in spider's web",
  "Hello me ... it's me again",
  "Hello me ... meet the real me",
  "Here I come again",
  "Here I come againwhoa!",
  "Here comes the reckoning day",
  "Hey! this was my fate",
  "Hey! this was my life",
  "Hey... look around you",
  "Hiding from everyone",
  "High priests of holocaustfire from the sea",
  "Hindsight is always 20-20",
  "His body fuels the power fire",
  "His limitations",
  "His manpussy was sold",
  "His neck in time to see",
  "His nightmare unfolds",
  "Hit them in their sleep",
  "Hit them in their sleep",
  "Hmmm-mmm cause your ass belongs to me!",
  "Holocaust",
  "Holy wars",
  "How could it end this way?",
  "How do you do? my name is trouble",
  "How history had forebode us",
  "How long I hold my breath",
  "How to live?",
  "Hunting the abyss lord, hunting the abyss lord",
  "Hurling through the air",
  "Hypnosis guides my hand",
  "Hypocrite the word that fits"],
  "I" => ["I feel it draw me in",
  "I make out my sweaty face",
  "I ain't death trip but I ain't automatic",
  "I am nuclear murderer I am polaris",
  "I am your ruler! land, sea and air",
  "I can't help but think,",
  "I can't replace the lies that let a 1000 days go",
  "I can't see the things that make true happiness I must be blind",
  "I don't know where I've been",
  "I forgot my name",
  "I forgot you said \"one day you'll walk alone\"",
  "I got no friends 'cause they read the papers",
  "I guess I should feel sorry",
  "I had no idea what it'd cost",
  "I had wrists donning slits",
  "I haven't got to yet",
  "I helped the blind to see",
  "I hope the end is less painful than my life",
  "I know it would surely break",
  "I know that somewhere, someone hears my voice",
  "I know they were doing it to you",
  "I know what I said now I must scream of the overdose",
  "I know who didn't show to mourn",
  "I like cancer to their bones",
  "I like the things that you try to fake",
  "I like the way that I make you itch",
  "I like the way that you fool yourself",
  "I like the way that you let me in",
  "I like the way that you stand in line",
  "I like the way that your stomach knots",
  "I like the way you stay on attack",
  "I look above and see",
  "I lost my life to the killing road",
  "I lost my mind I lost all my money",
  "I loved you anyway",
  "I master five magics I master five magics",
  "I master magics five I master magics five",
  "I miss the warm embrace I felt",
  "I need a ride to the morgue",
  "I need someone to show me the things in life that I can't find",
  "I need to be me'cause you're all too clear",
  "I opened doors for little old ladies",
  "I realized life was a game",
  "I rule on land air and sea",
  "I said I need youdoes that make me wrong?",
  "I saw a former pass away",
  "I saw a new earth today",
  "I saw a new earth today",
  "I saw my funeral that day",
  "I say...",
  "I should have known you'd crush me",
  "I slipside through the walkways",
  "I spin you round again",
  "I spread disease like a dog",
  "I stalk the cobwebbed stairways",
  "I stand on trial before the gods",
  "I tell you to enjoy life I wish I could but it's too late",
  "I thought I had it made",
  "I thought I knew",
  "I thought I knew it all",
  "I throw the switch",
  "I used to be such a sweet, sweet thing",
  "I want to rule this kingdom",
  "I warn you of the fate",
  "I went to church incognito",
  "I will give you life",
  "I will make for you",
  "I won't feel the hurt",
  "I'll have one more yesterday",
  "I'll just go back downhill",
  "I'm as mad as a hatter",
  "I'd love to stay with you all",
  "I'll be clicking off the miles",
  "I'll ever speak",
  "I'll go to hell for heaven's sake",
  "I'll leave it up to you: oh problem",
  "I'm a dirt torpedo",
  "I'm addicted to chaos",
  "I'm blowing on my cards",
  "I'm chomping at the bit",
  "I'm chomping at the bit ",
  "I'm coming in for the kill...",
  "I'm doing you a favor",
  "I'm in trouble for the things",
  "I'm not going to wake up today",
  "I'm not trash any longer",
  "I'm off to meet my maker",
  "I'm on my way to impact taste the high speed dirt",
  "I'm sharpening the axe",
  "I'm sharpening the axe",
  "I'm the sun that beats your brow in",
  "I'm tied up to the tracks",
  "I'm using my feet for my human machine",
  "I'm your master",
  "I've stepped over lots of bodies on my way",
  "If folds like a contortionist",
  "If I get up to the top I know",
  "If I see the morning hours",
  "In a black tie and straight jacket",
  "In the sockets of my eyes",
  "Irrational youths stop to stare",
  "It pulls my flesh away",
  "If I \"ain't superstitious\" then this won't mean a thing",
  "If I die before I wake",
  "If I die before I wake",
  "If he can be a nice boy",
  "If he wakes up we'll see",
  "If my heart was still alive",
  "If the war inside my head",
  "If you're fighting to live",
  "Ignorant religion \"holy wars\" and the dying",
  "Ignore the guilt and take your turn",
  "Immense in my girth: erect I stand tall",
  "Impervious to damage",
  "Impossible to break these walls",
  "In a cesspool I became dead",
  "In a dream I cannot see",
  "In her way I'll surely die",
  "In my opinions as a professional I recommend",
  "In my place I escape",
  "In our beliefs there's lie",
  "In our bodies there's die",
  "In our business there's sin",
  "In our life there's if",
  "In perpetual writhing",
  "In the millennium of the blind",
  "In the black cloak of night",
  "In the dark of dawn patrol",
  "In the eye of the tornadoblow me away",
  "In this bed I made for me",
  "In velvet gloves of sin",
  "Incarcerated with no possibility of parole for life",
  "Inside the big house",
  "Instruments to sight the stars",
  "Insufficient funds insanity and suicide",
  "Is this my final stand?",
  "Is turn around run through it man",
  "Is where I sleepI really feel",
  "It ain't called getting even",
  "It always starts again",
  "It can't be worse than this",
  "It gives me a migraine headache",
  "It might be in your homelands",
  "It turns to ashes in your mouth",
  "It was doomed to not be right",
  "It was just another day",
  "It was just another fight",
  "It was words strung into sentences",
  "It's ok to die!",
  "It's a funny thinga funny thing",
  "It's just another haul",
  "It's just too damn long that's allyeah",
  "It's our secretyou and me",
  "It's the kiss of death",
  "It's time to be immortal'cause heroes never die",
  "It's too much fun of being alive",
  "It's true you reap what you sow",
  "Its metal brain corrodes"],
  "J" => ["Jackyl speaking with tongue",
  "Je dois partir",
  "Je vous aime",
  "Joining hands with wicked ones",
  "Jump or die!",
  "Just a pawnthe last martyr dies",
  "Just be a bad dream",
  "Just can't see it from this far",
  "Just downright mean",
  "Just like the pied piper",
  "Just like the change of season",
  "Just may not be my turn"],
  "K" => ["Kill many and you're a conqueror",
  "Kill them all ... ooh ... oh you're a god!",
  "Killed a few feet from the cages",
  "Killing for religion",
  "Know it all scholar"],
  "L" => ["Ladies and gentlemen of the jury",
  "Ladies and gents we're still alive",
  "Launch the polaris the end doesn't scare us",
  "Leaping from the sky",
  "Led rats through the streets",
  "Let me be the protege of five magics",
  "Let me show youhow I love you",
  "Let the ceremony consecrate the marriage",
  "Let's do it!",
  "Let's get one thing straight",
  "Liars anagram is \"lairs\"",
  "Life systems disconnect",
  "Life's fabric is corrupt",
  "Life? ... what do ya mean life? ... I ain't got a life",
  "Lights shined on my path,",
  "Like a genie in a bottle",
  "Like the walls are closing in",
  "Listen up... I warn you",
  "Live and die within your heart",
  "Lock him in a rubber room",
  "Love and war they say all is fair",
  "Love's a tide pool",
  "Luck deserted me and the truth",
  "Lucretia rocks away",
  "Lucretia waits impatiently",
  "Lying on your bed"],
  "M" => ["Man I'm gonna try again",
  "My body fights for air",
  "My ears are overcome with noise",
  "My lungs begin to tear",
  "Madness comesand madness goes",
  "Magic if you pleasebring him to his knees",
  "Make a joke and I will sigh and you will laugh and I will cry",
  "Make sweet the breeze now defiled",
  "Make up the rules for me to live by",
  "Man still has one belief",
  "Man you were never even there",
  "Mankind has got to know",
  "Many centuries ago",
  "May the past \"rust in peace\" in \"hangar 18\"",
  "Maybe I don't like itbut I have no choice",
  "Maybe not a mutantmaybe a man",
  "Means to an end ended in disgrace",
  "Melting down all metalsturning plows and sheats to swords",
  "Memories are whirling by yeah",
  "Men rise on stepping stones of their",
  "Mess with the bull and you'll get the horn.",
  "Miserythe word that fits",
  "Monitoring all wages",
  "Monkey on my backaching my bones",
  "Moonbeams surge through the sky",
  "More anything",
  "More borrowed moneymore borrowed",
  "More borrowed moneymore borrowed time",
  "More that it's gonna hurt him",
  "Most valued possessions",
  "Moving on is a simple thing",
  "My air is getting thin",
  "My blood flows through the streets",
  "My body's gone that's all",
  "My boxcar life o' style",
  "My brain was laboredmy head would spin",
  "My brain was just some driftwood",
  "My broken body in a wreck",
  "My cat clawed my eye",
  "My creation",
  "My dad's had to hide",
  "My dog bit me on the leg today",
  "My flesh is bubbling up",
  "My friends all say",
  "My future looks so bright",
  "My heart was blackenedit's bloody red",
  "My icy fingers claw your back",
  "My judgement was life in hell",
  "My legion's when we do the crime",
  "My legs are paralyzed",
  "My life is fading fast",
  "My life passed before my eyes",
  "My mom's been thrown out of the society circle",
  "My only friend's the goat",
  "My past erasedno more disgrace",
  "My poison fills your head",
  "My systems locked in on military gluttons",
  "My thinking is derailed",
  "My wet brain neighbor cranes"],
  "N" => ["Never mind the tree",
  "No one plays they only die",
  "Nature's scales are forced to tip",
  "Never die",
  "Never disclosenever betray",
  "Never endingtill the black curtains falls",
  "Never knowing if I'd wake up in a",
  "Never sat-is-fied",
  "New world order comes in stages",
  "New world order will hold the mass",
  "New world orderyou shall be shown",
  "New ideas will surely get by",
  "Next mistake...no more mistakes!",
  "Next thing you knowthey'll take my thoughts away",
  "Nice story ... tell it to reader's digest!!!",
  "No confession all is known",
  "No contest nowhere to run",
  "No deed or dividend. some may ask \"why?\"",
  "No escaping pain",
  "No foolish naive stand",
  "No horse ever ran as fast",
  "No matter whatI keep coming back",
  "No more mister clean",
  "No more mister nice guy",
  "No more left only one",
  "No more living trapped inside",
  "No one knew what would happen there",
  "No one spoke no one even dared",
  "No time for questions",
  "No time for the games",
  "Non-stop combatant",
  "Not a cyborg",
  "Not as you do",
  "Not even close",
  "Not for the money not for the fame",
  "Not for the power just no more games",
  "Not from the tears just self abuse",
  "Not from the years not from the use",
  "Now I can only laugh",
  "Now I lay me down to sleep",
  "Now I think I've seen the light",
  "Now he's nothing for no one nowhere to see",
  "Now there's method to the madness",
  "Now there's motives for the suspect",
  "Now there's nothing left to say",
  "Now there's society to pay",
  "Now we've rewritten history",
  "Now with new hope some will be proud",
  "Now you've acquitted me",
  "Nowone day I started telling everyone that",
  "Nuclear winter spreading disease"],
  "O" => ["Of the countless corpses piled up along the wailing wall",
  "Offering their death kiss to me",
  "Oh what what you gonna do problem problem",
  "Oh what you gonna do?",
  "Oh yeah",
  "Oh, what do you expect me to do?",
  "Oh, what you gonna do with your problem?",
  "On judgement day",
  "On all counts for crimes against all humanity",
  "On the dresser in my room",
  "On the train of consequences",
  "Once stalked beneath your shadow",
  "Once you committed me",
  "Once you've been marked it's finished done",
  "One decree that stands alone",
  "One hour from now",
  "One last look at visions of flesh",
  "One man rules the earth",
  "One side of his face a kiss",
  "Only left alone",
  "Only makes me stronger",
  "Only one will stay alive: only one will stay alive",
  "Only yesterday they told me you were gone",
  "Ooh to close the drawer",
  "Our environment was wrecked",
  "Out to change the world"],
  "P" => ["Packed my bags and headed west",
  "Paid by the allianceto slay all the giants",
  "Pain of \"hook in mouth\"\"in my darkest hour\"",
  "Palms are getting wetsweating bullets",
  "Parade the grey robed monks",
  "Paralyzed with fear",
  "Part bionic",
  "Part of the master plan",
  "Pass judgement on humanity",
  "Paybacks are a bitch",
  "People clutter in the gutter",
  "People have round shoulders from fairing heavy loads",
  "People think I'm insane because I am frowning all the time",
  "Personal holocaust",
  "Perspective is lost in the spirit of the chase",
  "Pillars of pain and thorns",
  "Place all your trust here in me",
  "Please smile when you think of me",
  "Please smilesmile when you think about me",
  "Point blankyou're so courageous ...",
  "Point the finger",
  "Political breakthrougheuphoria's high",
  "Pontius pilate still washing his hands",
  "Population loves polaris",
  "Possessed with hellish tormentpossessed with hellish torment",
  "Possibly I've seen too much",
  "Praise your architecture of aggression",
  "Pray the lord my soul to keep",
  "Pray the lord to take",
  "Pray... don't find me",
  "Praying for death",
  "Pressure of the sound",
  "Pretending not to notice",
  "Problemhave you got a problem?",
  "Problemproblemproblemthe problem is you",
  "Problemwell you got a problem.",
  "Problemwellwhat you gonna do?",
  "Prophesied \"last rites/loved to death\" my friends",
  "Proven true to late",
  "Pseudo-safari the hunt is canned ...",
  "Psychotron",
  "Pulling out your poisoned fangs",
  "Punched me in the nose",
  "Push me to a breakpoint breakpoint",
  "Push push push me to a breakpoint",
  "Pushing me push push me to a breakpoint",
  "Put me down to lift you up"],
  "Q" => ["Quickest way out: quickest relief wins"],
  "R" => ["Raving impossibilities",
  "Raised in a form of living hell",
  "Random turmoil builds in me",
  "Rapes peacetakes life",
  "Ready to pounce at the touch of a button",
  "Receive a reprieve and be a pioneer",
  "Remember that you said",
  "Reminisce in the attic",
  "Rest assured these things I know",
  "Revelation come to pass",
  "Revelation has come to pass",
  "Rise so high; yet so far to fall",
  "Roach egg laying in my brain",
  "Roaring through my head",
  "Rotten egg air of death wrestles your nostrils",
  "Rules you break and just let it slide",
  "Run for coverrun"],
  "S" => ["Slight of hand and quick exchange",
  "Sacriledge and blasphemy",
  "Satan rears his ugly headto spit into the wind",
  "Secure and safe in open arms",
  "Sedate himheavily",
  "See the earth below",
  "Selective amnesia's the story",
  "Self esteem you seem to lack",
  "Self suffering since you were born",
  "Selves to higher things",
  "Sensors indicate",
  "Serpent swims free in my blood",
  "Set the ball a-rollin",
  "Sets the stage today",
  "She will be your bride",
  "She will serve me too",
  "Shippin' drugs and guns",
  "Shot in cold bloodno chance to fight",
  "Shot through with corroded thread",
  "Shun words of the biblewe need implements of war",
  "Sick fascination for someone's disaster",
  "Silence speaks louder than words",
  "Sing a one note song of rage",
  "Sit in granny's rockin' chair",
  "Sitting up late at night",
  "Sleepwalking to the gallows",
  "Slipping away from an iron grip",
  "Snakes... surround me",
  "Sneak attacksrepel down the rocks",
  "So as you read this know my friends",
  "So beware in the shadows",
  "So courageous",
  "So the eyes of man are",
  "Sorun my child and hide your face",
  "Sotag my toe and don't forget",
  "Soaring to the sun",
  "Some day you too will know my pain",
  "Some people live to destroy me",
  "Some people risk to employ me",
  "Someone's forsaken you and me",
  "Something I don't understand",
  "Somewhere an electric chair awaits",
  "Somewhere there's a reason",
  "Soon to make a crater",
  "Sorrow paid for valor is too much to recall",
  "Speak of mutually assured destruction?",
  "Spilling blood across the land",
  "Squeeze the trigger that makes you man",
  "Start kicking ass",
  "Still alive",
  "Still feel like I'm giong down I hear a distant wailing cry",
  "Still we sleepwalk off to work",
  "Suffocatingno one hears my calls",
  "Superstitious dust left twisting in the wind",
  "Surely that like the cat waiting",
  "Surely will not stand",
  "Survival such a silly whim",
  "Suspended state of cryogenics",
  "Swaying to the symphony of destruction",
  "Sweating bullets",
  "Sweet taste of vindication",
  "Symbol of society today"],
  "T" => ["Take life from tomorrow",
  "Taunting rigor mortis",
  "The gun in my mouth was real",
  "The more I try to read your lips",
  "The more of me I see reflect",
  "The more of you that I inspect",
  "The more the mask you're wearing rips",
  "The old tricks have been rearranged",
  "The ripping of the tissue",
  "The searing of the sinew",
  "The steam finally dissipates",
  "There is only death and danger",
  "There's a prison in my mind",
  "Try on this tie",
  "Take a look and see",
  "Take his life",
  "Take no prisonerscremate them",
  "Take no prisonerstake no shit",
  "Take some time to show you around",
  "Talkin' 'bout no dream",
  "Talkin' 'bout no vision",
  "Tangled abstract fallacy",
  "Target to destroy",
  "Taste copper on my tongue",
  "Taste me",
  "Taste the waters life's abundant",
  "Tears streak his solemn stare",
  "Technologythe battle's unfair",
  "Tell the truthyou wouldn't dare",
  "Tell them...",
  "Ten diademsto rule them allto crown them all",
  "Than to educate our sons? sorry but",
  "Than-thou-could-be-messenger of god",
  "Thanks for the information don't need no",
  "That I cannot explain",
  "That that doesn't kill me",
  "That's a problemproblemproblem",
  "That's what 911 is for",
  "That's what they did",
  "Thay take you away and they throw away the key",
  "The bride of frankenstein",
  "The harlot puddles for her lies",
  "The netherworld and sheol",
  "The panzers willpermeate them",
  "The answer to your question is ...",
  "The behavior's quite insane",
  "The big cat's left it's cage",
  "The body stayed but inside the head",
  "The cobra so eloquently glints",
  "The cradle and the grave",
  "The crystal ball's energized",
  "The day of final conflict",
  "The earth starts to rumble",
  "The end is finally here",
  "The end is nearit's crystal clear",
  "The finish line for me",
  "The golden chance for me",
  "The harder the rules became",
  "The heartland criesloss of all pride",
  "The hunt is canned",
  "The land of opportunity",
  "The last hope of man on earth",
  "The laying down of arms",
  "The lesson's mine to learn",
  "The military intelligence",
  "The mind was on the run",
  "The more insatiable the sex",
  "The more seriously I took things",
  "The more swelled our tongues became",
  "The one that ends it all",
  "The one thing we've found out",
  "The only way out of pain",
  "The other genocide",
  "The pale horse awaits",
  "The plans we made are back up on the road",
  "The primordial ooze",
  "The problem is you",
  "The problem is youproblem",
  "The problem is youyou got a problem",
  "The rain comes downcold wind blows",
  "The road will never end",
  "The secret of the family tree",
  "The skin and thophyoh so rare",
  "The sky is crumbling in",
  "The smell of death permeates the silk within my coffin lays",
  "The spoils of war are yours to keep",
  "The spoils of wars are yours to keep.",
  "The stage is setnow pay the price",
  "The stair creaksI precariously sneak",
  "The third world war",
  "The tigers eat their young",
  "The train of consequences",
  "The venom never goes away",
  "The vestal virginswheel the wyvern's in",
  "The warheads will all rust in peace",
  "The way you look when the walls cave in",
  "The white lights a train",
  "The world don't want to be saved",
  "The worldreligion at his feet",
  "The wounded of the wars",
  "Then I started seeing \"bad omens\" in my head",
  "There ain't no turning back",
  "There is nothing left of us",
  "There is one thing I can do",
  "There is something wrong with me",
  "There is something wrong with you",
  "There's bad news creeping up",
  "There's nothing more to say",
  "There's nothing special about the road",
  "There's three pointing back",
  "Thermal count is rising",
  "These are the last words",
  "They can't be seen with me",
  "They don't want you and they don't want me",
  "They killed my wifeand my baby",
  "They know a doctorgonna take you away",
  "They lived and they died",
  "They never die",
  "They say he's sickhe's obscene",
  "They've pulled my plug the picture fades",
  "Think I'll lose my mind if I don't find something to pacify",
  "Thinking down to your level",
  "This day will surely come",
  "This is itthis is the countdown to extinction",
  "This is no hoaxno one pushed out",
  "This is now",
  "This is nowtoday",
  "This is the part of me that hates",
  "This morning I made the call",
  "This song ain't over 'til the",
  "This taught guy's now a bitch",
  "This was my fate",
  "This was my life",
  "This was the road to destiny",
  "This was the road to my ruin",
  "This was the wrong one to be doing",
  "This was the wrong thing to do",
  "Those visions never seen",
  "Thrown to the wolves",
  "Time to pay with your ass",
  "Time to ride the skies",
  "Time's uparmageddon",
  "To catch another plane",
  "To eliminate your enemy",
  "To eliminate your enemy",
  "To envelop its prey below",
  "To envelop its prey below",
  "To get there early is on time",
  "To leave ain't believingso try and be tried",
  "To more air pollution warnings",
  "To overdose",
  "To people like methere is no order",
  "To raise the swords and shields",
  "To the elysian fields",
  "Too many problemsoh why am I here?",
  "Too wet to come in from the rain,",
  "Total dismay as the sun passed away",
  "Tornado nearly got me by the \"skin o' my teeth\"",
  "Tremble you weakings cower in fear",
  "True enemy or false friend?",
  "Turn bad days into good",
  "Turn breakdowns into blocks: I smashed 'em",
  "Turn up my collar welcome the unknown",
  "Two words combined that can't make sense",
  "Typhusdeteriate them"],
  "U" => ["Uneasy feeling burning out my eyes",
  "Unlike your love for me",
  "Until all is lost",
  "Up here in the air this will never hurt",
  "Up into my hideout",
  "Up on my soap box a leader",
  "Upon my podiumas the",
  "Used to control and command"],
  "V" => ["Vengence is mine",
  "Vested in me by the state I hereby sentence you to be"],
  "W" => ["We know how to and sure as shit we'll win",
  "We're not ready to see you yet",
  "With two feet in the grave",
  "Wringing my hands in dismay",
  "Wage the war on organized crime",
  "Walking stiff let me tell ya",
  "War is peace sure man",
  "Was my destiny someone said",
  "Watch him become a god",
  "Watch peoples heads a'roll",
  "Watching pain is your only pleasure",
  "We ain't going nowhere 'cause heroes never die",
  "We are storming the heavens",
  "We are the damned of all the world",
  "We ascend to our destiny",
  "We dance like marionettes",
  "We don't always see them",
  "We end our lives as moles",
  "We run for you than asia",
  "We straight-jacket the son-of-a-b**ch",
  "We'd be going anywhere telling people",
  "We've been hung out to dry",
  "We've been run down every hill",
  "Welcome it with a smile",
  "Welcome to our fortress tall",
  "Welcome to tomorrow!",
  "Well it's full speed ahead",
  "Wellme ... it's nice talking to myself",
  "Wellwhat you gonna do with your problem",
  "Well... I don't know... it's gonna hurt me",
  "What it leaves behind is hard",
  "When I found out how little I accomplished",
  "When the earth was cold as ice",
  "When will this cease",
  "When you hear them saying \"trust me\"",
  "Where do we go from here?",
  "Where evil lives and evil rules",
  "Where have the apostles gone?",
  "Where's the helping hand?",
  "While our nervous systems jerk",
  "Whirlpool got redundant",
  "Who will help me up?",
  "Who'd believe we'd spend more",
  "Who'd believe with the way things are here",
  "Who's to say what's for me to say...be...do",
  "Why somethings just fall through",
  "Why things don't go my way",
  "Why things go like they do",
  "Will disappear off the face of the planet",
  "Will surely also diewill surely also die",
  "Will surely live the lie",
  "Will we give warnings only time will tell",
  "Will you turn on me?",
  "Winds blow from the bowels of hell",
  "With 666 between his horns",
  "With blood upon their wings",
  "With hopes to enslave me",
  "With mud and strawblood and sweat",
  "With sadness in our hearts",
  "With the green house in effect",
  "Without eyes they could not see",
  "Without the mark you shall die",
  "Wizardall knowing all wise",
  "Won't stop 'til I hit the ground I'm on my way for sure",
  "Won't take a day off I'll be dead",
  "World leaders sell missiles cheap",
  "World powers fall",
  "Wrapped around a tree"],
  "X" => ["Xenon sinking"],
  "Y" => ["Yellow streak right up my spine",
  "You show and tell with greatest ease",
  "Yea, just keep on thinking it's my fault",
  "Yes, we have your honour we find the defendant guilty!",
  "You are here for me",
  "You belong to me",
  "You can subdue but never tame me",
  "You didn't want us anyway",
  "You don't do what you want and you fade away",
  "You feel my fingertips",
  "You got a problem the problem is you",
  "You got your body in suspension",
  "You got your brains dehydrated",
  "You know the sleeping feel no more pain",
  "You know your worth when your enemies",
  "You laugh and infect",
  "You pull the hammer without a care",
  "You push me to a breakpoint breakpoint",
  "You realize you are prey for me",
  "You take a mortal man",
  "You tell us how to run our lives",
  "You try and find you inside of me",
  "You try to take its pulse",
  "You will kill for me",
  "You will terminate",
  "You won't forget my lips",
  "You won't need your breath",
  "You work for mejust stay ecstatic",
  "You work for meliving for the screen",
  "You work for meyou're working nine-to-five",
  "You'll become one",
  "You'll feel my cold breath",
  "You'll find the solutionthe answers in the sky",
  "You'll get a kick in the teeth",
  "You'll grow to loathe my name",
  "You'll hate me just the same",
  "You'll serve only me",
  "You're mine",
  "You're one",
  "You're pushing me to a breakpoint",
  "You're pushing me to a breakpoint...",
  "You're pushing mepushpush me",
  "Your body has parts",
  "Your currency is obsolete",
  "Your family tree waits in the dark",
  "Your journey too shall end below",
  "Your stomach turns your flesh creeps",
  "Your tongue twist perverse",
  "Your wheelchair"],
  "Z" => ["Zero in on you"]}

  TITLE =
    [
    "Kansas: A Liturgy",
    "A Hand held by Another",
    "A Shopping Mall Somewhere in America",
    "A Ballad from the Far East",
    "A Thorn in Red China's Rose",
    "Stardom...Lifestyle & Excess",
    "An American Dream Redux",
    "On the Road to Lake Michigan",
    "Statue of Pocahantos, in a Museum in Omaha",
    "View of the Grand Canyon",
    "Elegy for Robert Johnson",
    "Summer at Yellowstone National Park",
    "Cuban Reverie",
    "For Henry David Thoreau",
    "For Betsy Ross",
    "Chain Gang Song, or Field Holler",
    "Harlem...A Remembrance",
    "Thank You Miami Skyscraper",
    "Remembering Allen Ginsberg",
    "A Farm in Connecticut",
    "6:30 PM, Times Square, I saw her Face",
    "Forget Mindfucking You...The Suburbs",
    "A Hotel in Texas",
    "A Parking lot in Nevada",
    "At Old South Church",
    "Disco Dance for Congress",
    "In Vietnam",
    "Venice Beach, Shabbat Dinner",
    "Psalm for Jesse Jackson",
    "An Alaskan Eskimo Family",
    "On Interstate 90"
    ]
end
